# Generated by Django 3.2.5 on 2022-02-24 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taplist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='brews',
            new_name='beer',
        ),
    ]
